name = "tgworkhoursbot"
main = "src/worker.js"
compatibility_date = "2024-09-10"
workers_dev = true

# Weekly cron: Saturday 23:59 PHT (= 15:59 UTC)
[triggers]
crons = ["59 15 * * SAT"]

# Bind your existing KV namespace
[[kv_namespaces]]
binding = "HOURS"
id = "b89428e4fdaa45f59e8bb9373c8392e5"

[vars]
TZ_OFFSET = "8"     # PHT (UTC+8)
PAY_RATE  = "2.5"
